### ISSUE TITLE
slonik Numbers look Wrong

### ISSUE THREAD

**Issue by mudgen** [porsager/postgres-benchmarks#2]
It seems that the biggest competitor to postgres is [slonik](https://github.com/gajus/slonik). So it seems like the slonik benchmark is the most important and useful one to have.  But the numbers look wrong.

**Comment by porsager** [comment]
Well slonik is not a driver, it's just an opinionated layer on top of `pg`, so I wouldn't say they compare much. Even so, the numbers will probably be the same as `pg` or slower, so they could be used as guidance. I already spent enough time figuring out how to make slonik work without luck, but I'm open to PR's if someone else wants to debug / dive in? 😉

**Comment by gajus** [comment]
Publishing wrong numbers is disingenuous to say the least. Slonik is just a layer on top of [`pg`](https://github.com/gajus/slonik/blob/master/package.json#L28). Their performance profiles are supposed to be near identical.

**Comment by porsager** [comment]
I'll remove them if you like, but why not submit a PR to get the correct numbers instead? I can honestly say I tried my best to figure out how to use Slonik properly, and the benchmarks aren't that complicated, so would be nice if you would take a look to see if it's something obvious I did wrong?

**Comment by porsager** [comment]
The implementation is right here:

https://github.com/porsager/postgres-benchmarks/blob/master/slonik/index.js

**Comment by gajus** [comment]
I will follow up in a day or two. This caught me in a busy time.

**Comment by porsager** [comment]
Sure thing. I've removed the mention of slonik in the readme for now, so no rush.

**Comment by gajus** [comment]
Would you mind trying out with the latest Slonik version?

I believe that the culprit was the rest query, which has since been removed.

https://github.com/gajus/slonik/commit/635500299cb6c694d0dc56fe4bd11039bacb284c

I tried running the benchmark myself, but as there are no instructions, it seems to just hang without doing anything.

**Comment by gajus** [comment]
I could not figure out how to run these benchmarks, so I've written a simple benchmark suite.

https://github.com/gajus/slonik/tree/master/benchmark

@porsager Feel free to copy these over.

**Comment by porsager** [comment]
It's just `npm i && node index.js`. 

It appears the missing part was `captureStackTrace: false`.

**Comment by porsager** [comment]
Should be correct now ;) 

I've re-added slonik, updated all libs to the latest verison and updated the results.
