### ISSUE TITLE
The comparison is not correct

### ISSUE THREAD

**Issue by stalniy** [porsager/postgres-benchmarks#4]
In benchmarking, you use template string literal for Postgres.js which is interpreted as a prepared statement but in all rest libraries you used raw query (not prepared one). 

This page describes how to do this in pg: https://node-postgres.com/features/queries

**Comment by porsager** [comment]
That's correct @stalniy, but this was also to showcase the difference in the idiomatic usage of each library.

I'll get that point added to the readme though.
